# Generated by Django 4.2.3 on 2023-07-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ascendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_primero', models.CharField(max_length=30)),
                ('apellido_segundo', models.CharField(max_length=30)),
                ('nombre_padre', models.CharField(max_length=30)),
                ('nombre_madre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_primero', models.CharField(max_length=30)),
                ('apellido_segundo', models.CharField(max_length=30)),
                ('estado_residencia', models.CharField(max_length=30)),
                ('ciudad_residencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_estudios', models.CharField(max_length=30)),
                ('puesto', models.CharField(max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('maestria', models.BooleanField()),
            ],
        ),
    ]
